---
- name: download tomcat
  get_url:
    url: https://dlcdn.apache.org/tomcat/tomcat-10/v10.1.33/bin/apache-tomcat-10.1.33.tar.gz
    dest: /home/maha/apache-tomcat-10.1.33.tar.gz
    force_basic_auth: yes
- name: creat tomcat folder
  file:
    path: /opt/tomcat 
    state: directory

- name: extract tomcat tar file
  unarchive:
    src: /home/maha/apache-tomcat-10.1.33.tar.gz
    dest: /opt/tomcat
    remote_src: yes