---
- name: create group
  group:
    name: tomcat
    state: present

- name: Create user
  user:
    name: tomcat
    shell: /bin/false
    home: /opt/tomcat
    group: tomcat
    state: present

  
